// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJdwc6fPgdDPxIsdrBjlWWOD_povb62co',
    appId: '1:1090569077187:web:a58bf52cbef328af643d76',
    messagingSenderId: '1090569077187',
    projectId: 'eformation-c0fcb',
    authDomain: 'eformation-c0fcb.firebaseapp.com',
    storageBucket: 'eformation-c0fcb.firebasestorage.app',
    measurementId: 'G-Z48CY9JZ1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDTotInuaUU_AFAT211t9VpJbrZaPgys',
    appId: '1:1090569077187:android:31caf6d97bf6fa6c643d76',
    messagingSenderId: '1090569077187',
    projectId: 'eformation-c0fcb',
    storageBucket: 'eformation-c0fcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNELUcroEIVOJ9s2mkxxd1DkZaulWqaAs',
    appId: '1:1090569077187:ios:ca33d5e3056ec4ea643d76',
    messagingSenderId: '1090569077187',
    projectId: 'eformation-c0fcb',
    storageBucket: 'eformation-c0fcb.firebasestorage.app',
    iosBundleId: 'com.example.homeworkHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNELUcroEIVOJ9s2mkxxd1DkZaulWqaAs',
    appId: '1:1090569077187:ios:ca33d5e3056ec4ea643d76',
    messagingSenderId: '1090569077187',
    projectId: 'eformation-c0fcb',
    storageBucket: 'eformation-c0fcb.firebasestorage.app',
    iosBundleId: 'com.example.homeworkHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6QYTZ81JBtgenA4MHtEMTcehUkmv_dJY',
    appId: '1:1090569077187:web:43d4dcc4e885a158643d76',
    messagingSenderId: '1090569077187',
    projectId: 'eformation-c0fcb',
    authDomain: 'eformation-c0fcb.firebaseapp.com',
    storageBucket: 'eformation-c0fcb.firebasestorage.app',
    measurementId: 'G-4WSZWW09XV',
  );
}
